create table if not exists person (
  id   bigint generated by default as identity primary key,
  name text not null
);

create table if not exists marriage (
  id          bigint generated by default as identity primary key,
  partner1_id bigint not null references person(id) on delete cascade,
  partner2_id bigint not null references person(id) on delete cascade
);

create table if not exists parent_child (
  parent_id bigint not null references person(id) on delete cascade,
  child_id  bigint not null references person(id) on delete cascade,
  primary key (parent_id, child_id)
);

create index if not exists idx_marriage_p1 on marriage(partner1_id);
create index if not exists idx_marriage_p2 on marriage(partner2_id);
create index if not exists idx_pc_parent  on parent_child(parent_id);
create index if not exists idx_pc_child   on parent_child(child_id);
