create table if not exists person (
  id               bigint generated by default as identity primary key,
  first_name       text not null,
  last_name        text,
  photo_url        text,
  gender           text,
  uuid             uuid,
  email            text,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid(),
  updated_by_email text        default (auth.jwt() ->> 'email'),
  updated_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email'),
  updated_at       timestamptz not null default now()
);

create table if not exists marriage (
  id               bigint generated by default as identity primary key,
  partner1_id      bigint not null references person(id) on delete cascade,
  partner2_id      bigint not null references person(id) on delete cascade,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid()
);

create table if not exists parent_child (
  parent_id        bigint not null references person(id) on delete cascade,
  child_id         bigint not null references person(id) on delete cascade,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid(),
  primary key (parent_id, child_id)
);

create table if not exists app_settings (
  id                smallint primary key default 1,
  default_person_id bigint references person(id) on delete set null,
  updated_by_email  text,
  updated_at        timestamptz default now(),
  constraint app_settings_single_row check (id = 1)
);

alter table person add column if not exists first_name       text;
alter table person add column if not exists last_name        text;
alter table person add column if not exists photo_url        text;
alter table person add column if not exists gender           text;
alter table person add column if not exists uuid             uuid;
alter table person add column if not exists email            text;
alter table person add column if not exists created_by       uuid        default auth.uid();
alter table person add column if not exists created_by_email text        default (auth.jwt() ->> 'email');
alter table person add column if not exists created_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email');
alter table person add column if not exists created_at       timestamptz not null default now();
alter table person add column if not exists updated_by       uuid        default auth.uid();
alter table person add column if not exists updated_by_email text        default (auth.jwt() ->> 'email');
alter table person add column if not exists updated_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email');
alter table person add column if not exists updated_at       timestamptz not null default now();

alter table marriage add column if not exists created_by       uuid        default auth.uid();
alter table marriage add column if not exists created_by_email text        default (auth.jwt() ->> 'email');
alter table marriage add column if not exists created_at       timestamptz not null default now();
alter table marriage add column if not exists updated_by       uuid        default auth.uid();

alter table parent_child add column if not exists created_by       uuid        default auth.uid();
alter table parent_child add column if not exists created_by_email text        default (auth.jwt() ->> 'email');
alter table parent_child add column if not exists created_at       timestamptz not null default now();
alter table parent_child add column if not exists updated_by       uuid        default auth.uid();

create unique index if not exists person_uuid_key on person(uuid);

create index if not exists idx_marriage_p1 on marriage(partner1_id);
create index if not exists idx_marriage_p2 on marriage(partner2_id);
create index if not exists idx_pc_parent   on parent_child(parent_id);
create index if not exists idx_pc_child    on parent_child(child_id);

alter table person       enable row level security;
alter table marriage     enable row level security;
alter table parent_child enable row level security;
alter table app_settings enable row level security;

drop policy if exists "read person"        on person;       create policy "read person"        on person       for select using (true);
drop policy if exists "read marriage"      on marriage;     create policy "read marriage"      on marriage     for select using (true);
drop policy if exists "read parent_child"  on parent_child; create policy "read parent_child"  on parent_child for select using (true);
drop policy if exists "read app_settings"  on app_settings; create policy "read app_settings"  on app_settings for select using (true);

drop policy if exists "write person"       on person;       create policy "write person"       on person       for all to authenticated using (true) with check (true);
drop policy if exists "write marriage"     on marriage;     create policy "write marriage"     on marriage     for all to authenticated using (true) with check (true);
drop policy if exists "write parent_child" on parent_child; create policy "write parent_child" on parent_child for all to authenticated using (true) with check (true);
drop policy if exists "write app_settings" on app_settings; create policy "write app_settings" on app_settings for all to authenticated using (true) with check (true);
