create table person (
  id               bigint generated by default as identity primary key,
  first_name       text not null,
  last_name        text,
  photo_url        text,
  gender           text,
  uuid             uuid,
  email            text,
  approved         boolean not null default false,
  is_admin         boolean not null default false,
  last_requested_at timestamptz,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid(),
  updated_by_email text        default (auth.jwt() ->> 'email'),
  updated_by_name  text        default coalesce(auth.jwt() -> 'user_metadata' ->> 'full_name', auth.jwt() -> 'user_metadata' ->> 'name', auth.jwt() ->> 'email'),
  updated_at       timestamptz not null default now()
);

create table marriage (
  id               bigint generated by default as identity primary key,
  partner1_id      bigint not null references person(id) on delete cascade,
  partner2_id      bigint not null references person(id) on delete cascade,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid()
);

create table parent_child (
  parent_id        bigint not null references person(id) on delete cascade,
  child_id         bigint not null references person(id) on delete cascade,
  created_by       uuid        default auth.uid(),
  created_by_email text        default (auth.jwt() ->> 'email'),
  created_at       timestamptz not null default now(),
  updated_by       uuid        default auth.uid(),
  primary key (parent_id, child_id)
);

create table app_settings (
  id                smallint primary key default 1,
  default_person_id bigint references person(id) on delete set null,
  owner_email       text,
  app_url           text,
  from_email        text,
  updated_by_email  text,
  updated_at        timestamptz default now(),
  constraint app_settings_single_row check (id = 1)
);

create table app_user (
  id                uuid primary key,
  email             text,
  first_name        text,
  last_name         text,
  approved          boolean not null default false,
  is_admin          boolean not null default false,
  last_requested_at timestamptz,
  created_at        timestamptz not null default now()
);

create table user_person (
  user_id    uuid        primary key references app_user(id) on delete cascade,
  person_id  bigint      not null references person(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index person_uuid_key on person(uuid);
create index idx_marriage_p1 on marriage(partner1_id);
create index idx_marriage_p2 on marriage(partner2_id);
create index idx_pc_parent   on parent_child(parent_id);
create index idx_pc_child    on parent_child(child_id);

create function public.is_approved() returns boolean
  language sql security definer set search_path = public stable as
$fn$ select exists (select 1 from app_user where id = auth.uid() and approved) $fn$;

create function public.is_admin() returns boolean
  language sql security definer set search_path = public stable as
$fn$ select exists (select 1 from app_user where id = auth.uid() and is_admin) $fn$;

create function public.send_email(p_to text, p_subject text, p_html text) returns void
  language plpgsql security definer set search_path = public as
$fn$
declare
  v_key text;
  v_from text;
begin
  begin
    select decrypted_secret into v_key from vault.decrypted_secrets where name = 'email_api_key';
    if v_key is null or p_to is null then
      return;
    end if;
    select coalesce(from_email, owner_email) into v_from from app_settings where id = 1;
    if v_from is null then
      return;
    end if;
    perform net.http_post(
      url := 'https://api.sendgrid.com/v3/mail/send',
      headers := jsonb_build_object('Authorization', 'Bearer ' || v_key, 'Content-Type', 'application/json'),
      body := jsonb_build_object(
        'personalizations', jsonb_build_array(jsonb_build_object('to', jsonb_build_array(jsonb_build_object('email', p_to)))),
        'from', jsonb_build_object('email', v_from, 'name', 'Family Tree'),
        'subject', p_subject,
        'content', jsonb_build_array(jsonb_build_object('type', 'text/html', 'value', p_html))
      )
    );
  exception when others then
    null;
  end;
end;
$fn$;

create function public.send_access_email(p_first text, p_last text, p_email text) returns void
  language plpgsql security definer set search_path = public as
$fn$
declare
  v_to text;
  v_app text;
  v_name text;
begin
  select owner_email, app_url into v_to, v_app from app_settings where id = 1;
  if v_to is null then
    return;
  end if;
  v_name := coalesce(nullif(btrim(coalesce(p_first, '') || ' ' || coalesce(p_last, '')), ''), 'Someone');
  perform public.send_email(
    v_to,
    v_name || ' is requesting access to your family tree',
    '<p><strong>' || v_name || '</strong>' ||
    case when p_email is not null then ' (' || p_email || ')' else '' end ||
    ' is waiting for your approval. Open ' ||
    case when v_app is not null then '<a href="' || v_app || '">your family tree</a>' else 'your family tree app' end ||
    ', tap Members, and Approve.</p>'
  );
end;
$fn$;

create function public.bootstrap_owner() returns trigger
  language plpgsql security definer set search_path = public as
$fn$
begin
  new.email := auth.jwt() ->> 'email';
  if new.id = auth.uid() and new.email = (select owner_email from app_settings where id = 1) then
    new.approved := true;
    new.is_admin := true;
  else
    new.approved := false;
    new.is_admin := false;
  end if;
  return new;
end;
$fn$;

create function public.guard_user_flags() returns trigger
  language plpgsql security definer set search_path = public as
$fn$
begin
  if not public.is_admin() then
    new.approved := old.approved;
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$fn$;

create function public.notify_access_request() returns trigger
  language plpgsql security definer set search_path = public as
$fn$
begin
  if new.approved is not true then
    perform public.send_access_email(new.first_name, new.last_name, new.email);
  end if;
  return new;
end;
$fn$;

create function public.notify_access_granted() returns trigger
  language plpgsql security definer set search_path = public as
$fn$
declare
  v_app text;
begin
  if new.email is not null and new.approved is true and old.approved is distinct from true then
    select app_url into v_app from app_settings where id = 1;
    perform public.send_email(
      new.email,
      'You are in - family tree access approved',
      '<p>Good news - your access to the family tree has been approved. Open ' ||
      case when v_app is not null then '<a href="' || v_app || '">the family tree</a>' else 'the family tree app' end ||
      ' and sign in.</p>'
    );
  end if;
  return new;
end;
$fn$;

create function public.request_access() returns void
  language plpgsql security definer set search_path = public as
$fn$
declare
  u app_user;
begin
  select * into u from app_user where id = auth.uid();
  if u.id is null or u.approved is true then
    return;
  end if;
  if u.last_requested_at is not null and u.last_requested_at > now() - interval '30 minutes' then
    return;
  end if;
  update app_user set last_requested_at = now() where id = auth.uid();
  perform public.send_access_email(u.first_name, u.last_name, u.email);
end;
$fn$;

grant execute on function public.request_access() to authenticated;

create trigger bootstrap_owner_trg before insert on app_user for each row execute function public.bootstrap_owner();
create trigger guard_user_flags_trg before update on app_user for each row execute function public.guard_user_flags();
create trigger notify_access_request_trg after insert on app_user for each row execute function public.notify_access_request();
create trigger notify_access_granted_trg after update on app_user for each row execute function public.notify_access_granted();

alter table person       enable row level security;
alter table marriage     enable row level security;
alter table parent_child enable row level security;
alter table app_settings enable row level security;
alter table app_user     enable row level security;
alter table user_person  enable row level security;

grant select, insert, update, delete on app_user to authenticated;
grant select, insert, update, delete on user_person to authenticated;

create policy person_select on person for select using (public.is_approved());
create policy person_insert on person for insert to authenticated with check (public.is_approved());
create policy person_update on person for update to authenticated using (public.is_approved()) with check (public.is_approved());
create policy person_delete on person for delete to authenticated using (public.is_approved());

create policy marriage_rw on marriage for all to authenticated using (public.is_approved()) with check (public.is_approved());
create policy parent_child_rw on parent_child for all to authenticated using (public.is_approved()) with check (public.is_approved());

create policy app_settings_select on app_settings for select to authenticated using (public.is_approved());
create policy app_settings_write on app_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy app_user_select on app_user for select to authenticated using (id = auth.uid() or public.is_admin());
create policy app_user_insert on app_user for insert to authenticated with check (id = auth.uid());
create policy app_user_update on app_user for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy user_person_select on user_person for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy user_person_insert on user_person for insert to authenticated with check (user_id = auth.uid() or public.is_admin());
create policy user_person_update on user_person for update to authenticated using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy user_person_delete on user_person for delete to authenticated using (user_id = auth.uid() or public.is_admin());
